version: "3"

services:
  container:
    build: ./container
    ports:
      - 3300:3300
    volumes:
      - ./frontend:/frontend
      - ./common:/common
      - ./backend:/backend
    networks:
      - postgres
    environment:
      - DB_HOST=db_deploy
      - JWT_SECRET=somesecret

    depends_on:
      - db_deploy

  db_deploy:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    ports:
      - 5432:5432
    volumes:
    - ./postgres:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin_a_deploy:
    image: dpage/pgadmin4:4.23
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
    - ./value/pgadmin:/var/lib/pgadmin
    depends_on:
      - db_deploy
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
